; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:demo_f070f6]
platform = ststm32
board = demo_f070f6
framework = stm32cube
upload_protocol = stlink
upload_flags = -c adapter serial 303030303030303030303031
;debug_tool = stlink
;build_flags = -Wl,-u_printf_float

